name: ala_hawa
description: "A news app that reads from mysecondhometv.com"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  firebase_analytics: ^10.8.6
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.0.0
  webfeed: ^0.7.0
  flag: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/ala_hawa_logo.png
